create table if not exists daily_logs (
  id bigint generated by default as identity primary key,
  date date not null unique,
  weight numeric(5,2),
  waist numeric(5,2),
  calories integer,
  protein integer,
  steps integer,
  water numeric(4,2),
  sleep numeric(4,2),
  habits jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
